Repository KBfinance-team-MetalWallet/metal-wallet-backend, pull requests merged in 2024-10, with the labels that each got.

#34 배포를 위한 GitHub Actions 설정
  .github/workflow/deploy.yml
  src/main/java/com/kb/wallet/global/common/response/ApiResponse.java
  src/main/java/com/kb/wallet/global/config/AppConfig.java
Labels: deploy

#40 계좌(Account) 관련 domain, dto에 bankLogo, bankName, color 필드 추가
  src/main/java/com/kb/wallet/account/domain/Account.java
  src/main/java/com/kb/wallet/account/dto/AccountRequest.java
  src/main/java/com/kb/wallet/account/dto/AccountResponse.java
Labels: feature

#50 Fix: Account 변수명 통일
  src/main/java/com/kb/wallet/account/domain/Account.java
  src/main/java/com/kb/wallet/account/dto/response/AccountResponse.java
Labels: feature

#52 ticket 스크롤 페이징 구현
  src/main/java/com/kb/wallet/ticket/controller/TicketController.java
  src/main/java/com/kb/wallet/ticket/repository/TicketRepository.java
  src/main/java/com/kb/wallet/ticket/service/TicketService.java
  src/main/java/com/kb/wallet/ticket/service/TicketServiceImpl.java
Labels: feature

#51 Feat: RSA 암호화 및 Ticket 도메인 리팩토링
  src/main/java/com/kb/wallet/account/dto/response/TransactionRecordResponse.java
  src/main/java/com/kb/wallet/account/repository/AccountRepository.java
  src/main/java/com/kb/wallet/account/repository/TransactionRecordRepository.java
  src/main/java/com/kb/wallet/account/service/AccountService.java
  src/main/java/com/kb/wallet/global/common/response/ApiResponse.java
  src/main/java/com/kb/wallet/global/common/response/ErrorResponse.java
  src/main/java/com/kb/wallet/global/common/response/ErrorResponseDto.java
  src/main/java/com/kb/wallet/global/config/SecurityConfig.java
  src/main/java/com/kb/wallet/global/exception/CustomError.java
  src/main/java/com/kb/wallet/jwt/JwtFilter.java
  src/main/java/com/kb/wallet/jwt/TokenProvider.java
  src/main/java/com/kb/wallet/member/controller/MemberController.java
  src/main/java/com/kb/wallet/member/domain/Member.java
  src/main/java/com/kb/wallet/member/dto/request/LoginMemberRequest.java
  src/main/java/com/kb/wallet/member/dto/request/PinNumberVerificationRequest.java
  src/main/java/com/kb/wallet/member/dto/request/RegisterMemberRequest.java
  src/main/java/com/kb/wallet/member/dto/response/MemberResponse.java
  src/main/java/com/kb/wallet/member/dto/response/RegisterMemberResponse.java
  src/main/java/com/kb/wallet/member/repository/MemberMapper.java
  src/main/java/com/kb/wallet/member/repository/MemberRepository.java
  src/main/java/com/kb/wallet/member/service/CustomUserDetailsService.java
  src/main/java/com/kb/wallet/member/service/MemberService.java
  src/main/java/com/kb/wallet/member/service/MemberServiceImpl.java
  src/main/java/com/kb/wallet/musical/controller/MusicalController.java
  src/main/java/com/kb/wallet/musical/dto/response/MusicalDetailResponse.java
  src/main/java/com/kb/wallet/musical/dto/response/MusicalResponse.java
  src/main/java/com/kb/wallet/musical/repository/MusicalMapper.java
  src/main/java/com/kb/wallet/musical/service/MusicalServiceImpl.java
  src/main/java/com/kb/wallet/qrcode/dto/EncrypeDataDto.java
  src/main/java/com/kb/wallet/qrcode/dto/request/DecryptionRequest.java
  src/main/java/com/kb/wallet/qrcode/dto/request/EncryptionRequest.java
  src/main/java/com/kb/wallet/qrcode/dto/response/DecryptionResponse.java
  src/main/java/com/kb/wallet/qrcode/dto/response/EncryptionResponse.java
  src/main/java/com/kb/wallet/qrcode/service/RSAService.java
  src/main/java/com/kb/wallet/qrcode/service/RSAServiceImpl.java
  src/main/java/com/kb/wallet/seat/dto/response/SectionAvailability.java
  src/main/java/com/kb/wallet/seat/service/SeatServiceImpl.java
  src/main/java/com/kb/wallet/test/controller/TestController.java
  src/main/java/com/kb/wallet/test/service/TestService.java
  src/main/java/com/kb/wallet/test/service/TestServiceImpl.java
  src/main/java/com/kb/wallet/ticket/controller/TicketController.java
  src/main/java/com/kb/wallet/ticket/domain/Schedule.java
  src/main/java/com/kb/wallet/ticket/domain/Ticket.java
  src/main/java/com/kb/wallet/ticket/dto/request/TicketExchangeRequest.java
  src/main/java/com/kb/wallet/ticket/dto/request/VerifyTicketRequest.java
  src/main/java/com/kb/wallet/ticket/dto/response/ProposedEncryptResponse.java
  src/main/java/com/kb/wallet/ticket/dto/response/TicketInfo.java
  src/main/java/com/kb/wallet/ticket/dto/response/TicketListResponse.java
  src/main/java/com/kb/wallet/ticket/dto/response/TicketResponse.java
  src/main/java/com/kb/wallet/ticket/model/TicketQrInfo.java
  src/main/java/com/kb/wallet/ticket/repository/TicketExchangeRepository.java
  src/main/java/com/kb/wallet/ticket/repository/TicketRepository.java
  src/main/java/com/kb/wallet/ticket/service/ScheduleServiceImpl.java
  src/main/java/com/kb/wallet/ticket/service/TicketService.java
  src/main/java/com/kb/wallet/ticket/service/TicketServiceImpl.java
Labels: bug, feature

#53 dev, prod 환경 분리
  build.gradle
  src/main/java/com/kb/wallet/global/config/AppConfig.java
  src/main/java/com/kb/wallet/global/config/DataSourceConfig.java
  src/main/java/com/kb/wallet/global/config/ProfileInitializer.java
  src/main/java/com/kb/wallet/global/config/SecurityConfig.java
  src/main/java/com/kb/wallet/global/config/WebAppInitializer.java
  src/main/java/com/kb/wallet/global/config/WebConfig.java
Labels: feature, refactoring, deploy

#55 Refactor: `Musical` 도메인 리팩터링 완료
  src/main/java/com/kb/wallet/musical/controller/MusicalController.java
  src/main/java/com/kb/wallet/musical/domain/Actor.java
  src/main/java/com/kb/wallet/musical/domain/Musical.java
  src/main/java/com/kb/wallet/musical/dto/request/MusicalCreationRequest.java
  src/main/java/com/kb/wallet/musical/dto/request/MusicalInfoUpdateRequest.java
  src/main/java/com/kb/wallet/musical/dto/response/MusicalCreationResponse.java
  src/main/java/com/kb/wallet/musical/dto/response/MusicalDetailResponse.java
  src/main/java/com/kb/wallet/musical/dto/response/MusicalInfoUpdateResponse.java
  src/main/java/com/kb/wallet/musical/dto/response/MusicalScheduleSeatAvailabilityResponse.java
  src/main/java/com/kb/wallet/musical/repository/MusicalMapper.java
  src/main/java/com/kb/wallet/musical/service/MusicalService.java
  src/main/java/com/kb/wallet/musical/service/MusicalServiceImpl.java
Labels: refactoring

#59 Refactor: 티켓 사용 관련 로직 수정 및 불필요한 코드 제거
  src/main/java/com/kb/wallet/ticket/constant/TicketStatus.java
  src/main/java/com/kb/wallet/ticket/controller/TicketController.java
  src/main/java/com/kb/wallet/ticket/domain/Ticket.java
  src/main/java/com/kb/wallet/ticket/dto/request/EncryptRequest.java
  src/main/java/com/kb/wallet/ticket/dto/request/SignedTicketRequest.java
  src/main/java/com/kb/wallet/ticket/exception/TicketException.java
  src/main/java/com/kb/wallet/ticket/repository/TicketExchangeRepository.java
  src/main/java/com/kb/wallet/ticket/repository/TicketRepository.java
  src/main/java/com/kb/wallet/ticket/service/TicketCheckService.java
  src/main/java/com/kb/wallet/ticket/service/TicketService.java
  src/main/java/com/kb/wallet/ticket/service/TicketServiceImpl.java
Labels: refactoring

#61 Refactor/rsa/ljr
  .gitignore
  src/main/java/com/kb/wallet/account/controller/AccountController.java
  src/main/java/com/kb/wallet/account/domain/Account.java
  src/main/java/com/kb/wallet/account/domain/TransactionRecord.java
  src/main/java/com/kb/wallet/account/dto/request/AccountRequest.java
  src/main/java/com/kb/wallet/account/dto/response/AccountResponse.java
  src/main/java/com/kb/wallet/account/dto/response/TransactionRecordResponse.java
  src/main/java/com/kb/wallet/account/exception/AccountNotFoundException.java
  src/main/java/com/kb/wallet/account/repository/AccountRepository.java
  src/main/java/com/kb/wallet/account/service/AccountService.java
  src/main/java/com/kb/wallet/account/service/AccountServiceImpl.java
  src/main/java/com/kb/wallet/global/common/status/ErrorCode.java
  src/main/java/com/kb/wallet/global/util/BouncyCastleUtil.java
  src/main/java/com/kb/wallet/global/util/RSAUtil.java
  src/main/java/com/kb/wallet/ticket/domain/Ticket.java
  src/main/java/com/kb/wallet/ticket/dto/request/EncryptRequest.java
  src/main/java/com/kb/wallet/ticket/service/RSAService.java
  src/main/java/com/kb/wallet/ticket/service/RSAServiceImpl.java
  src/main/java/com/kb/wallet/ticket/service/TicketService.java
  src/main/java/com/kb/wallet/ticket/service/TicketServiceImpl.java
Labels: refactoring

#60 Refactor: 불필요한 코드 제거
  src/main/java/com/kb/wallet/global/exception/CustomError.java
  src/main/java/com/kb/wallet/global/exception/CustomException.java
  src/main/java/com/kb/wallet/global/exception/DatabaseAccessException.java
Labels: refactoring

#58 Refactor: `Member` 도메인 리팩터링 완료
  src/main/java/com/kb/wallet/controller/HomeController.java
  src/main/java/com/kb/wallet/global/common/status/ErrorCode.java
  src/main/java/com/kb/wallet/member/controller/MemberController.java
  src/main/java/com/kb/wallet/member/domain/Member.java
  src/main/java/com/kb/wallet/member/dto/request/RegisterMemberRequest.java
  src/main/java/com/kb/wallet/member/dto/response/MemberResponse.java
  src/main/java/com/kb/wallet/member/repository/MemberMapper.java
  src/main/java/com/kb/wallet/member/repository/MemberRepository.java
  src/main/java/com/kb/wallet/member/repository/MemberRepositoryImpl.java
  src/main/java/com/kb/wallet/member/service/CustomUserDetailsService.java
  src/main/java/com/kb/wallet/member/service/MemberService.java
  src/main/java/com/kb/wallet/member/service/MemberServiceImpl.java
  src/main/java/com/kb/wallet/test/controller/TestController.java
  src/main/java/com/kb/wallet/test/service/TestService.java
  src/main/java/com/kb/wallet/test/service/TestServiceImpl.java
Labels: refactoring

#65 [Refactor] Ticket 도메인의 findByMember 쿼리 최적화
  src/main/java/com/kb/wallet/ticket/domain/Ticket.java
  src/main/java/com/kb/wallet/ticket/domain/TicketExchange.java
  src/main/java/com/kb/wallet/ticket/repository/TicketRepository.java
  src/main/java/com/kb/wallet/ticket/service/TicketServiceImpl.java
Labels: refactoring
